// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CoinRow: typeof import('./components/CoinRow.vue')['default']
    CoinTable: typeof import('./components/CoinTable.vue')['default']
    FiltersBar: typeof import('./components/FiltersBar.vue')['default']
  }
}
